rutcom/routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Livewire\UsersTable;
use App\Http\Livewire\Clients;
use App\Http\Livewire\ClientActive;
use App\Http\Livewire\ClientsExcel;
use App\Http\Livewire\ClientsMap;
use App\Http\Livewire\TableLocation;
use App\Http\Livewire\Calendar;
use App\Http\Controllers\TimeControl;
use App\Http\Livewire\Tasks;
use App\Http\Livewire\Listappointments;
use App\Http\Livewire\RutcomMap;
use App\Http\Livewire\UserPermits;
use App\Http\Livewire\CreateAppointmentForm;
use App\Http\Livewire\CreateLocationForm;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', function () {
    return view('dashboard');
})->name('dashboard');

Route::middleware(['auth:sanctum', 'verified'])->get('/users', UsersTable::class
)->name('users');
Route::middleware(['auth:sanctum', 'verified'])->get('/clients', Clients::class
)->name('clients');
Route::middleware(['auth:sanctum', 'verified'])->get('/tasks', Tasks::class
)->name('tasks');
Route::middleware(['auth:sanctum', 'verified'])->get('/appointments', Listappointments::class
)->name('appointments');
Route::middleware(['auth:sanctum', 'verified'])->get('/routesMap', RutcomMap::class
)->name('routeMap');
Route::middleware(['auth:sanctum', 'verified'])->get('/routes', TableLocation ::class
)->name('routes');
Route::resource('timecontrol',TimeControl::class);
Route::get('appointments/create', CreateAppointmentForm::class)->name('appointments.create');
Route::get('calendar', Calendar::class)->name('calendar');
Route::get('users/permits', UserPermits::class)->name('users.permits');
Route::get('clients/active', ClientActive::class)->name('clients.active');
Route::get('clients/export', ClientsExcel::class)->name('clients.export');
Route::get('routes/create', CreateLocationForm::class)->name('routes.create');
Route::get('routes/clients', ClientsMap::class)->name('routes.map');

rutcom/app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Fortify\TwoFactorAuthenticatable;
use Laravel\Jetstream\HasProfilePhoto;
use Laravel\Jetstream\HasTeams;
use Laravel\Sanctum\HasApiTokens;


class User extends Authenticatable
{
    use HasApiTokens;
    use HasFactory;
    use HasProfilePhoto;
    use HasTeams;
    use Notifiable;
    use TwoFactorAuthenticatable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
        'role_id',
        'status',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
        'two_factor_recovery_codes',
        'two_factor_secret',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    /**
     * The accessors to append to the model's array form.
     *
     * @var array
     */
    protected $appends = [
        'profile_photo_url',
    ];

    public function getStatusBadgeAttribute()
    {
    	$badges = [
    		'User' => 'primary',
    		'Admin' => 'success',
    	];

    	return $badges[$this->status];
    }
}

rutcom/app/Http/Livewire/AppointmentsCount.php
<?php
use Illuminate\Http\Request;
namespace App\Http\Livewire;
use App\Models\Appointment;
use App\Models\Client;
use App\Models\User;
use App\Models\Event;
use DB;
use Livewire\Component;

class AppointmentsCount extends Component
{

    public $appointmentsCount;
    public $clientsCount;
    public $usersCount;
    public $eventsCount;

    public function mount()
    {
        $this->getAppointmentsCount();
        $this->getClientsCount();
        $this->getUsersCount();
        $this->getEventsCount();
    }

    public function getAppointmentsCount($status = null)
    {
        $this->appointmentsCount = Appointment::query()
            ->when($status, function ($query, $status) {
                return $query->where('status', $status);
            })
            ->count();
    }

    public function getClientsCount($status = null)
    {
        $this->clientsCount = Client::query()
            ->when($status, function ($query, $status) {
                return $query->where('status', $status);
            })
            ->count();
    }
    public function getUsersCount($status = null)
    {
        $this->usersCount = User::query()
            ->when($status, function ($query, $status) {
                return $query->where('status', $status);
            })
            ->count();
    }

    public function getEventsCount($status = null)
    {
        $this->eventsCount = Event::query()
            ->when($status, function ($query, $status) {
                return $query->where('status', $status);
            })
            ->count();
    }




    public function render()
    {
        return view('livewire.appointments-count');
    }


}

rutcom/app/Http/Livewire/Calendar.php
<?php
namespace App\Http\Livewire;
use Livewire\Component;
use App\Models\Event;

class Calendar extends Component
{
    public $events = '';

    public function getevent()
    {
        $events = Event::select('id','title','start')->get();

        return  json_encode($events);
    }

    /**
    * Write code on Method
    *
    * @return response()
    */
    public function addevent($event)
    {
        $input['title'] = $event['title'];
        $input['start'] = $event['start'];
        Event::create($input);
    }

    /**
    * Write code on Method
    *
    * @return response()
    */
    public function eventDrop($event, $oldEvent)
    {
      $eventdata = Event::find($event['id']);
      $eventdata->start = $event['start'];
      $eventdata->save();
    }

    /**
    * Write code on Method
    *
    * @return response()
    */
    public function render()
    {
        $events = Event::select('id','title','start')->get();

        $this->events = json_encode($events);

        return view('livewire.calendar');
    }
}

rutcom/app/Http/Livewire/ChartClients.php
<?php

namespace App\Http\Livewire;
use Illuminate\Http\Request;
use App\Models\Client;
use DB;
use Livewire\Component;

class ChartClients extends Component
{
    public function render()
    { $populationClients = Client::select(
        DB::raw("year(created_at) as year"),
        DB::raw('count(*) as count'))

    ->orderBy(DB::raw("YEAR(created_at)"))
    ->groupBy(DB::raw("YEAR(created_at)"))
    ->get();


$res[] = ['Year', 'Clients'];
foreach ($populationClients as $key => $val) {
$res[++$key] = [$val->year, (int)$val->count];
}
        return view('livewire.chart-clients')->with('populationClients', json_encode($res));
    }
}

rutcom/app/Http/Livewire/Chartline.php
<?php

namespace App\Http\Livewire;
use Illuminate\Http\Request;
use App\Models\User;
use DB;
use Livewire\Component;

class Chartline extends Component
{
    public function render()
    { $population = User::select(
        DB::raw("year(created_at) as year"),
        DB::raw('count(*) as count'))

    ->orderBy(DB::raw("YEAR(created_at)"))
    ->groupBy(DB::raw("YEAR(created_at)"))
    ->get();


$res[] = ['Year', 'Users'];
foreach ($population as $key => $val) {
$res[++$key] = [$val->year, (int)$val->count];
}
        return view('livewire.chartline')->with('population', json_encode($res));
    }
}

rutcom/app/Http/Livewire/ClientActive.php
<?php

namespace App\Http\Livewire;
use App\Models\Client;
    use Livewire\WithPagination;
    use Illuminate\Support\Facades\Auth;
    use Livewire\Component;

class ClientActive extends Component
{
          use WithPagination;

            public $showModal = false;
            public $clientid;
            public $client;

            protected $rules = [
                'client.role_id' => 'required',
                'client.status'=>'required',

            ];
            protected $queryString = [
                'search' => ['except'=>''],
                'perPage' => ['except'=>'5'],

            ];

            public $search= '';
            public $perPage='5';



            public function render()

            {
                $role=Auth::user()->role_id;
                if($role =='1'){
                    return view('livewire.client-active',[
                    'clients' => Client::where('name','LIKE',"%{$this->search}%")
                    ->orWhere('email','LIKE',"%{$this->search}%")
                    ->paginate($this->perPage)
                ]);
            }

            else{
                return  abort(403);
            }
        }

            public function clear() {
                $this->search = '';
                $this->page = 1;
                $this->perPage= '5';
            }

            public function edit($clientid)
            {
                $this->showModal = true;
                $this->clientid= $clientid;
                $this->client = Client::find($clientid);
            }

            public function create()
            {
                $this->showModal = true;
                $this->client = null;
                $this->clientid= null;
            }

            public function save()
            {
                $this->validate();

                if (!is_null($this->clientid)) {
                    $this->client->save();
                } else {
                    Client::create($this->client);
                }
                $this->showModal = false;
            }

            public function close()
            {
                $this->showModal = false;
            }

            public function delete($id)
            {
                $client = Client::find($id);
                if ($client) {
                    $client->delete();
                }
            }

}

rutcom/app/Http/Livewire/Clients.php
<?php

namespace App\Http\Livewire;
use App\Models\Client;
use Livewire\WithPagination;
use Livewire\Component;

class Clients extends Component{

    use WithPagination;

    public $showModal = false;
    public $clientid;
    public $client;

    protected $rules = [

        'client.name' => 'required',
        'client.dni' => 'required',
        'client.email' => 'required',
        'client.address' => 'required',
        'client.status'=>'required',





    ];

    protected $queryString = [
        'search' => ['except'=>''],
        'perPage' => ['except'=>'5'],

    ];

    public $search= '';
    public $perPage='5';

    public function render(){
            return view('livewire.clients',[
            'clients' => Client::where('name','LIKE',"%{$this->search}%")
            ->orWhere('email','LIKE',"%{$this->search}%")
            ->paginate($this->perPage)
        ]);
    }

    public function clear() {
        $this->search = '';
        $this->page = 1;
        $this->perPage= '5';
    }

    public function edit($clientid){
        $this->showModal = true;
        $this->clientid= $clientid;
        $this->client = Client::find($clientid);
        $this->dispatchBrowserEvent('swal:modal', [
            'type' => 'success',
            'title' => 'Record updated successfully',
            'text' => '',
        ]);
    }

    public function create(){
        $this->showModal = true;
        $this->client = null;
        $this->clientid= null;
        $this->dispatchBrowserEvent('swal:modal', [
            'type' => 'success',
            'title' => 'Record added successfully',
            'text' => '',
        ]);
    }

    public function save(){
        $this->validate();

        if (!is_null($this->clientid)) {
            $this->client->save();
        } else {
            Client::create($this->client);
        }
        $this->showModal = false;
    }

    public function close(){
        $this->showModal = false;
    }

    public function delete($id){
        $client = Client::find($id);
        if ($client) {
            $client->delete();
        }
    }
}

rutcom/app/Http/Livewire/ClientsExcel.php
<?php

namespace App\Http\Livewire;

use App\Models\Client;
use Livewire\Component;
use App\Exports\ClientExport;
use Maatwebsite\Excel\Facades\Excel;
use Symfony\Component\HttpFoundation\Response;
use Illuminate\Support\Facades\Auth;

class ClientsExcel extends Component
{

    public $selectedClients = [];

    public $clients;



    public function mount()
    {
        $this->clients = Client::all();
    }



    public function export($ext)
    {
        abort_if(!in_array($ext, ['csv', 'xlsx', 'pdf']), Response::HTTP_NOT_FOUND);

        return Excel::download(new ClientExport($this->selectedClients), 'clients.' . $ext);
    }

    public function render(){
    $role=Auth::user()->role_id;
    if($role =='1'){
        return view('livewire.clients-excel');
        }
     else{
        return  abort(403);
    }
    }
}

rutcom/app/Http/Livewire/ClientsMap.php
<?php

namespace App\Http\Livewire;
use Mapper;
use Livewire\Component;
use App\Models\Location;

class ClientsMap extends Component
{
    public $location;

    public function render()
    {   $location=Location::all();

        Mapper::map(37.02700, -4.53864);

        foreach ($location as $value) {
            Mapper::informationWindow($value->latitude, $value->longitude,$value->content);
                 }

        return view('livewire.clients-map');
    }
}

rutcom/app/Http/Livewire/CreateAppointmentForm.php
<?php

namespace App\Http\Livewire;
use Illuminate\Support\Facades\Validator;
use App\Models\Appointment;
use App\Models\Client;
use App\Models\User;
use Livewire\Component;


class CreateAppointmentForm extends Component
{
	public $state = [
		'status' => 'SCHEDULED',
	];

	public function createAppointment()
	{
		Validator::make(
			$this->state,
			[   'user_id'=>'required',
				'client_id' => 'required',
				'date' => 'required',
				'time' => 'required',
				'note' => 'nullable',
				'status' => 'required|in:SCHEDULED,CLOSED',
			],
			[
				'client_id.required' => 'The client field is required.'
			])->validate();

		Appointment::create($this->state);

		$this->dispatchBrowserEvent('swal:modal', [
            'type' => 'success',
            'title' => 'Record added successfully',
            'text' => '',
        ]);
	}

    public function render()

    {   $clients = Client::all();
        $users=User::all();
        return view('livewire.create-appointment-form', [
        	'clients' => $clients,
            'users'=>$users,
        ]);
    }
}

rutcom/app/Http/Livewire/CreateLocationForm.php
<?php

namespace App\Http\Livewire;

use Livewire\Component;
use Illuminate\Support\Facades\Validator;
use App\Models\Location;
use App\Models\Client;

class CreateLocationForm extends Component
{
    public $state;
    public function createlocation()
	{
		Validator::make(
			$this->state,
			[
				'user_id' =>  'requiered',
				'latitude' => 'required',
				'longitude' => 'required',
				'content' => 'nullable',

			])->validate();


		Location::create($this->state);

		$this->dispatchBrowserEvent('swal:modal', [
            'type' => 'success',
            'title' => 'Record added successfully',
            'text' => '',
        ]);
	}

    public function render()

    {   $clients = Client::all();

        return view('livewire.create-location-form', [
        	'clients' => $clients,

            ]);
    }

}

rutcom/app/Http/Livewire/FooterRutcom.php
<?php

namespace App\Http\Livewire;

use Livewire\Component;

class FooterRutcom extends Component
{
    public function render()
    {
        return view('livewire.footer-rutcom');
    }
}

rutcom/app/Http/Livewire/RutcomMap.php
<?php

namespace App\Http\Livewire;
use Mapper;
use Livewire\Component;

class RutcomMap extends Component
{
    public function render()
    {   Mapper::map(37.02700, -4.53864);
        return view('livewire.rutcom-map');
    }
}

rutcom/app/Http/Livewire/ToggleButton.php
<?php

namespace App\Http\Livewire;
use Illuminate\Database\Eloquent\Model;
use Livewire\Component;

class ToggleButton extends Component
{
    public  $model;
    public  $field;

    public  $isActive;



    public function mount()
    {
        $this->isActive = (bool) $this->model->getAttribute($this->field);
    }
    public function render()
    {
        return view('livewire.toggle-button');
    }

    public function updating($field, $value)
    {
        $this->model->setAttribute($this->field, $value)->save();
    }

}

rutcom/resources/views/livewire/chart-clients.blade.php
<div  class="p-4 bg-white shadow-lg" id="linechartClients"></div>


<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
<script type="text/javascript">
    var populationClients = <?php echo $populationClients; ?>;
    console.log(populationClients);
    google.charts.load('current', {
        'packages': ['corechart']
    });
    google.charts.setOnLoadCallback(lineChart);

    function lineChart() {
        var data = google.visualization.arrayToDataTable(populationClients);
        var options = {
            title: 'Clients',
            curveType: 'function',
            legend: {
                position: 'bottom'
            }
        };
        var chart = new google.visualization.LineChart(document.getElementById('linechartClients'));
        chart.draw(data, options);
    }
</script>

rutcom/resources/views/livewire/chartline.blade.php
<div  class="p-4 bg-white shadow-lg" id="linechart"></div>


<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
<script type="text/javascript">
    var population = <?php echo $population; ?>;
    console.log(population);
    google.charts.load('current', {
        'packages': ['corechart']
    });
    google.charts.setOnLoadCallback(lineChart);

    function lineChart() {
        var data = google.visualization.arrayToDataTable(population);
        var options = {
            title: 'Users',
            curveType: 'function',
            legend: {
                position: 'bottom'
            }
        };
        var chart = new google.visualization.LineChart(document.getElementById('linechart'));
        chart.draw(data, options);
    }
</script>

rutcom/resources/views/livewire/clients-map.blade.php
 <x-slot name="header">
    <h2 class="text-xl font-semibold leading-tight text-gray-800">
        {{ __('Route') }}
    </h2>
</x-slot>

        <div class="py-12">
        <div class="mx-auto max-w-7xl sm:px-6 lg:px-8">
            <div class="overflow-hidden bg-white shadow-xl sm:rounded-lg">
                <div style="height: 600px; width: 1220px;">
                    {!!Mapper::render()!!}
                    </div>
            </div>
        </div>
    </div>

rutcom/resources/views/livewire/listappointments.blade.php
<x-slot name="header">
    <h2 class="text-xl font-semibold leading-tight text-gray-800">
        {{ __('Appointments') }}
    </h2>
</x-slot>

<div class="py-12">
    <div class="mx-auto max-w-7xl sm:px-6 lg:px-8">
        <div class="overflow-hidden bg-white shadow-xl sm:rounded-lg">
            <div class="content">
                <div class="container-fluid">

                  <div class="row">
                    <div class="col-lg-12">
                        <div class="mb-2 d-flex justify-content-between">
                        <div>
                            <a href="{{ route('appointments.create') }}">

                            <button class= 'inline-flex items-center px-4 py-2 text-xs font-semibold tracking-widest text-white uppercase transition bg-gray-800 border border-transparent rounded-md hover:bg-gray-700 active:bg-gray-900 focus:outline-none focus:border-gray-900 focus:ring focus:ring-gray-300 disabled:opacity-25'> Add New Appointment</button>
                          </a>

                          @if ($selectedRows)
                          <div class="ml-2 btn-group">
                            <button type="button" class="btn btn-default">Bulk Actions</button>
                            <button type="button" class="btn btn-default dropdown-toggle dropdown-icon" data-toggle="dropdown">
                              <span class="sr-only">Toggle Dropdown</span>
                            </button>
                            <div class="dropdown-menu" role="menu">
                              <a wire:click.prevent="deleteSelectedRows" class="dropdown-item" href="#">Delete Selected</a>
                              <a wire:click.prevent="markAllAsScheduled" class="dropdown-item" href="#">Mark as Scheduled</a>
                              <a wire:click.prevent="markAllAsClosed" class="dropdown-item" href="#">Mark as Closed</a>
                            </div>
                          </div>

                          <span class="ml-2">selected {{ count($selectedRows) }} {{ Str::plural('appointment', count($selectedRows)) }}</span>
                          @endif

                        </div>
                        <div class="btn-group">
                          <button wire:click="filterAppointmentsByStatus" type="button" class="btn {{ is_null($status) ? 'btn-secondary' : 'btn-default' }}">
                            <span class="mr-1">All</span>
                            <span class="badge badge-pill badge-info">{{ $appointmentsCount }}</span>
                          </button>

                          <button wire:click="filterAppointmentsByStatus('scheduled')" type="button" class="btn {{ ($status === 'scheduled') ? 'btn-secondary' : 'btn-default' }}">
                            <span class="mr-1">Scheduled</span>
                            <span class="badge badge-pill badge-primary">{{ $scheduledAppointmentsCount }}</span>
                          </button>

                          <button wire:click="filterAppointmentsByStatus('closed')" type="button" class="btn {{ ($status === 'closed') ? 'btn-secondary' : 'btn-default' }}">
                            <span class="mr-1">Closed</span>
                            <span class="badge badge-pill badge-success">{{ $closedAppointmentsCount }}</span>
                          </button>
                        </div>
                        </div>
                      <div class="card">
                        <div class="card-body">
                          <table class="table table-hover">
                                    <thead>
                                      <tr>
                                <th>
                                  <div class="ml-2 icheck-primary d-inline">
                                    <input wire:model="selectPageRows" type="checkbox" value="" name="todo2" id="todoCheck2">
                                    <label for="todoCheck2"></label>
                                  </div>
                                </th>
                                        <th scope="col">#</th>
                                        <th scope="col">Client Name</th>
                                <th scope="col">Date</th>
                                <th scope="col">Time</th>
                                        <th scope="col">Status</th>
                                        <th scope="col">Assigned</th>
                                        <th scope="col">Options</th>
                                      </tr>
                                    </thead>
                                    <tbody>
                              @foreach ($appointments as $appointment)
                                      <tr>
                                <th>
                                  <div class="ml-2 icheck-primary d-inline">
                                    <input wire:model="selectedRows" type="checkbox" value="{{ $appointment->id }}" name="todo2" id="{{ $appointment->id }}">
                                    <label for="{{ $appointment->id }}"></label>
                                  </div>
                                </th>
                                        <th scope="row">{{ $loop->iteration }}</th>
                                        <td>{{ $appointment->client->name }}</td>
                                        <td>{{ $appointment->date }}</td>
                                <td>{{ $appointment->time }}</td>
                                <td>
                                  <span class="badge badge-{{ $appointment->status_badge }}">{{ $appointment->status }}</span>
                                </td>
                                <td>{{ $appointment->user->name }}</td>
                                        <td>
                                            <button
                                            class="inline-flex items-center px-4 py-2 text-xs font-semibold tracking-widest text-white uppercase transition duration-150 ease-in-out bg-gray-800 border border-transparent rounded-md hover:bg-gray-700 active:bg-gray-900 focus:outline-none focus:border-gray-900 focus:shadow-outline-gray disabled:opacity-25"
                                            wire:click.prevent="edit({{ $appointment->id }})">Edit
                                        </button>

                                        <button
                                        class="inline-flex items-center px-4 py-2 text-xs font-semibold tracking-widest text-white uppercase transition duration-150 ease-in-out bg-red-600 border border-transparent rounded-md focus:outline-none focus:border-gray-900 focus:shadow-outline-gray disabled:opacity-25"
                                        wire:click.prevent="delete({{ $appointment->id }})"
                                        onclick="confirm('Are you sure?') || event.stopImmediatePropagation()">Delete
                                    </button>
                                        </td>
                                      </tr>
                              @endforeach
                                    </tbody>
                                  </table>
                        </div>
                        <div class="card-footer d-flex justify-content-end">
                          {!! $appointments->links() !!}
                        </div>
                    </div>
                </div>
            </div>

        </div>

        <div class="@if (!$showModal) hidden @endif items-center justify-center fixed left-0 bottom-0 w-full h-full bg-gray-800 bg-opacity-90">
            <div class="w-1/2 bg-white rounded-lg">
                <form wire:submit.prevent="save" class="w-full">
                    <div class="flex flex-col items-start p-4">
                        <div class="flex items-center w-full pb-4 border-b">
                            <div class="text-lg font-medium text-gray-900">{{ $appointment->id ? 'Edit User' : 'Add New User' }}</div>
                            <svg wire:click="close"
                                 class="w-6 h-6 ml-auto text-gray-700 cursor-pointer fill-current"
                                 xmlns="http://www.w3.org/2000/svg" viewBox="0 0 18 18">
                                <path
                                    d="M14.53 4.53l-1.06-1.06L9 7.94 4.53 3.47 3.47 4.53 7.94 9l-4.47 4.47 1.06 1.06L9 10.06l4.47 4.47 1.06-1.06L10.06 9z"/>
                            </svg>
                        </div>
                        <div class="w-full">
                            <label for="user">Assigned:</label>
                            <select wire:model.defer="appointment.user_id" class="form-control">
                                <option value="">Select User</option>
                                @foreach($users as $user)
                                    <option value="{{ $user->id }}">{{ $user->name }}</option>
                                @endforeach
                            </select>

                        </div>
                        <div class="w-full">
                            <label for="appointmentTime">Appointment Date</label>
                                                <div class="mb-3 input-group">
                                                  <div class="input-group-prepend">
                                                    <span class="input-group-text"></span>
                                                  </div>
                                                  <x-datepicker wire:model.defer="appointment.date" id="appointmentDate"/>

                        </div>
                        <div class="w-full">
                            <label for="appointmentTime">Appointment Time</label>
                                                <div class="mb-3 input-group">
                                                  <div class="input-group-prepend">
                                                    <span class="input-group-text"></span>
                                                  </div>
                                                  <x-timepicker wire:model.defer="appointment.time" id="appointmentTime"/>
                                                  </div>
                        </div>

                        <div class="w-full">
                            <label for="note">Note:</label>
                            <textarea id="note" wire:model.defer="appointment.note" class="form-control"></textarea>
                        </div>
                        <div class="w-full">
                            <label class="block text-sm font-medium text-gray-700" for="title">
                                Status
                            </label>
                            <select wire:model.defer="appointment.status" class="block w-full mt-1 border-gray-300 rounded-md shadow-sm focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50">
                                <option value="Scheduled">Scheduled</option>
                                <option value="Closed">Closed</option>

                            </select>
                        </div>
                        <div class="ml-auto">
                            <button class="px-4 py-2 font-bold text-white bg-blue-500 rounded hover:bg-blue-700"
                                    type="submit">{{ $appointment->id ? 'Save Changes' : 'Save' }}
                            </button>
                            <button class="px-4 py-2 font-bold text-white bg-gray-500 rounded"
                                    wire:click="close"
                                    type="button"
                                    data-dismiss="modal">Close
                            </button>
                        </div>
                    </div>
                </form>
            </div>
 </div>
        </div>

rutcom/resources/views/livewire/rutcom-map.blade.php
<div style="width: 940px; height: 500px;">
	{!! Mapper::render() !!}
</div>